*W przestrzeni publicznej, gdy mówi się o programowaniu, często przedstawia się je jako coś trudnego i wymagającego długiego treningu. Tymczasem współczesne narzędzia programistyczne mogą być z łatwością używane przez każdego z dostępem do internetu. Na początku mogą wydawać się one nieco zastraszające – daleko odbiegają od znajomych interfejsów, szybko okazuje się, że ich używanie jest wygodne i satysfakcjonujące. Pozwalają na automatyzację żmudnych zadań, a korzystanie z nich często daje satysfakcję podobną do tej czerpanej z rozwiązywania łamigłówek logicznych.*

W tym kursie będziemy używać języka Python. Ma on trzy istotne zalety:
- Jest obecnie jednym z najpopularniejszych języków programowania, przez co łatwo znaleźć dotyczące go materiały dydaktyczne.
- Python jest stosunkowo prostym językiem, chociaż trudno jest mi wyjaśnić w tym momencie, na czym ta prostota polega.
- Python jest również najpopularniejszym językiem programowania używanym w analizie danych. Oferuje więc wiele narzędzi specyficznych dla tego zagadnienia. Z tego właśnie powodu Microsoft dodał obsługę Pythona do Excela.

Aby uruchomić program napisany w języku Python, należy najpierw zainstalować u siebie na komputerze interpreter tego języka wraz z biblioteką standardową i kilkoma innymi narzędziami. Interpreter jest programem tłumaczącym kod z języka programowania – zrozumiałego dla ludzi, na kod dający bezpośrednie instrukcje komputerowi. Instrukcję instalacji Pythona można znaleźć w [oficjalnej dokumentacji](https://docs.python.org/3.13/installing/index.html).

Na szczęście, na ten moment nie musimy się nawet tym martwić! Google udostępnia bezpłatnie usługę [Colab](https://colab.research.google.com/), oferującą bezpłatne notatniki, w których można używać Pythona. Notatniki pozwalają na mieszane komórek z kodem i komórek z tekstem. Każdą z nich można uruchamiać niezależnie i wielkokrotnie. Pozwala to wprowadzać zmiany i na bierząco testować ich efekty, przez co notatniki stanowią świetne narzędzie dydaktyczne i badawcze. Stwórz teraz nowy notatnik, a w pierwszej komórce wpisz 'print("Hello, World!")' i naciśnij kombinację klawiszy SHIFT+ENTER, aby zatwierdzić. Wynik powinien wyglądać mniej więcej tak:

In [1]:
print("Hello, World!")

Hello, World!

Po tym [rytuale](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program), możemy zabierać się do pracy.

## Skok na głęboką wodę

W programowaniu, jak w wielu innych dziedzinach życia, nie jest mądrze wymyślać koło na nowo. W praktyce programowania ciągle używa się narzędzi napisanych przez innych. Python pozwala w prosty sposób używać kodu z dostępnych na komputerze bibliotek dzięki słowu kluczowemu `import`. Na początek dwie biblioteki w następujący sposób:

In [2]:
import polars as pl
import kagglehub

W ten sposób zaimportowaliśmy dwie biblioteki. Pierwsza z nich - `Polars`, służy do pracy z tabelami. Druga - `kagglehub` jedynie ułatwi nam ściągnięcie z internetu potrzebnych danych. Wyjaśnienia wymaga tutaj jeszcze użycie słowa kluczowego `as`. Linia `import polars as pl` pozwala jednocześnie na używanie biblioteki `polars` i zmienia jej alias na krótsze i wygodniejsze przy częstym używaniu `pl`. Poza tym, taki alias jest używany w oficjalnej dokumentacji, przykładowo [tutaj](https://docs.pola.rs/user-guide/getting-started/#reading-writing). Nawiasem mówiąc, będę tutaj często załączał odnośniki do oficjalnej dokumentacji Pythona, Polars i innych bibliotek. Praca programisty bardzo często opiera się o czytanie dokumentacji cudzych programów i o pisanie dokumentacji własnych. Równie istotne jest też pisanie programów w sposób prosty do zrozumienia. Wrócimy do tego tematu w przyszłości. A teraz – do dzieła. Zaczniemy od pobrania statystyk samobójstw z lat 1979-2016.

In [3]:
path = kagglehub.dataset_download("szamil/who-suicide-statistics")

W powyższej instrukcji 'dataset_download' to, odniesienie do pewnej funkcji z biblioteki 'kagglehub'. Odwołujemy się do niej, łącząc nazwę modułu z nazwą funkcji kropką – 'kagglehub.dataset_download'. Funkcje w programowaniu mogą wykonywać pewne czynności, a następnie mogą zwracać wynik. Niektóre z funkcji wymagają jednego lub więcej argumentów podawanych w nawiasach, a oddzielonych przecinkami.

W przypadku funkcji 'kagglehub.dataset_download' argumentem jest nazwa zbioru danych, główna funkcjonalność to pobranie go na dysk, a wartość zwracana przez nią, to ścieżka do folderu z danymi.

W końcu, dodanie fragmentu 'path = ...' przed uruchomieniem funkcji sprawia, że wartość, którą zwraca, zostanie zapisane jako zmienna pod nazwą 'path'. Dzięki temu będziemy mogli odwoływać się do niej ponownie, na przykład tak:

In [4]:
print(path)

/home/filip/.cache/kagglehub/datasets/szamil/who-suicide-statistics/versions/1

Ścieżka ta pokazuje, w którym dokładnie folderze znajdują się pliki. Zaczynamy w folderze domowym `home`, potem przechodzimy do folderu użytkownika `filip` i tak dalej, aż trafiamy do folderu `1`. Nazwy folderów i plików oddzielane są ukośnikami prawymi, ale uwaga – w systemie Windows używane są do tego ukośniki lewe. Więcej informacji można znaleźć na [Wikipedii](https://pl.wikipedia.org/wiki/%C5%9Acie%C5%BCka_dost%C4%99pu). 

Skąd wiedzieliśmy natomiast, że argumentem powinno być akurat `"szamil/who-suicide-statistics"`? Tę informację widać na [kaggle](https://www.kaggle.com/datasets/szamil/who-suicide-statistics) po kliknięciu przycisku „download”. Na tej samej stronie można znaleźć informację, że w zbiorze danych znajduje się dokładnie jeden plik – `who_suicide_statistics.csv`. Aby otworzyć plik, musimy stworzyć ścieżkę bezpośrednio do niego. W tym celu do zmiennej path musimy dopisać jeszcze końcówkę `/who_suicide_statistics.csv`

In [5]:
path_to_data = path + "/who_suicide_statistics.csv"
print(path_to_data)

/home/filip/.cache/kagglehub/datasets/szamil/who-suicide-statistics/versions/1/who_suicide_statistics.csv

### Interludium na stringi

Wypada tutaj wyjaśnić szerzej, co dokładnie stało się w linijce 'path_to_data = path + "/who-suicide-statistics.csv"'. W języku Python tekst pisany w angielskich cudzysłowach jest typem danych odpowiadający zwykłemu tekstowi – 'string' (ang. *łańcuch*). Napis bez cudzysłowów – 'path', nie jest sam w sobie stringiem, a odniesieniem do pewnej wartości zapisanej wcześniej. To mamy na myśli, kiedy mówimy, że path jest zmienną. Kiedy używamy operatora dodawania na dwóch zmiennych typu 'string', to wynikiem jest 'string' powstały ze zlepienia ich ze sobą. Połączenie ścieżki zapisanej w zmiennej 'path' i nazwy pliku poprzedzonej ukośnikiem zapisaliśmy do nowej zmiennej – 'path_to_data'. Co do zasady nazwy zmiennych powinny zawierać jedynie litery angielskiego alfabetu i podkreślniki. Używanie innych znaków jest albo zakazane, albo niepraktyczne.

## Do roboty

Teraz jesteśmy gotowi zabrać się za dane. Do ich wczytywania i transformacji będziemy używać biblioteki 'Polars'. Ponieważ plik, który mamy, jest plikiem 'csv', to użyjemy funkcji stosownej do tego rodzaju pliku. W drugiej linijce użyjemy funkcji `head`, której zadaniem jest wyświetlenie pierwszych kilku wierszy danych.

In [6]:
df = pl.read_csv(path_to_data)
df.head(5)

shape: (5, 6)
┌─────────┬──────┬────────┬─────────────┬─────────────┬────────────┐
│ country ┆ year ┆ sex    ┆ age         ┆ suicides_no ┆ population │
│ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---         ┆ ---        │
│ str     ┆ i64  ┆ str    ┆ str         ┆ i64         ┆ i64        │
╞═════════╪══════╪════════╪═════════════╪═════════════╪════════════╡
│ Albania ┆ 1985 ┆ female ┆ 15-24 years ┆ null        ┆ 277900     │
│ Albania ┆ 1985 ┆ female ┆ 25-34 years ┆ null        ┆ 246800     │
│ Albania ┆ 1985 ┆ female ┆ 35-54 years ┆ null        ┆ 267500     │
│ Albania ┆ 1985 ┆ female ┆ 5-14 years  ┆ null        ┆ 298300     │
│ Albania ┆ 1985 ┆ female ┆ 55-74 years ┆ null        ┆ 138700     │
└─────────┴──────┴────────┴─────────────┴─────────────┴────────────┘

Udało się! Wczytaliśmy dane i zapisaliśmy do zmiennej 'df'. Ta zwyczajowa nazwa bierze się stąd, że typ danych odpowiadający takiej tabeli, to 'DataFrame'. Widzimy powyżej wszystkie sześć kolumn, jakie znajdują się w danych. Pod ich nazwami są skróty sygnalizujące jaki typ danych znajduje się w każdej z nich. Jak łatwo się domyślić 'str' odpowiada stringom. Druga sygnatura – 'i64', wskazuje na wartości typu 'integer', czyli liczby całkowite. Od razu widać pewien problem z danymi – w pierwszych linijkach kolumny 'suicides_no', zamiast liczb widać napisy 'null'. Oznacza to, że te wartości są puste.

Specjaliści z zakresu analizy danych napisali już za dużo słów na temat tego, co robić z pustymi wartościami. My je po prostu usuniemy, a wynik takiej operacji zapiszemy do nowej zmiennej.

In [7]:
df_clean = df.drop_nulls()
df_clean.head(6)

shape: (6, 6)
┌─────────┬──────┬────────┬─────────────┬─────────────┬────────────┐
│ country ┆ year ┆ sex    ┆ age         ┆ suicides_no ┆ population │
│ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---         ┆ ---        │
│ str     ┆ i64  ┆ str    ┆ str         ┆ i64         ┆ i64        │
╞═════════╪══════╪════════╪═════════════╪═════════════╪════════════╡
│ Albania ┆ 1987 ┆ female ┆ 15-24 years ┆ 14          ┆ 289700     │
│ Albania ┆ 1987 ┆ female ┆ 25-34 years ┆ 4           ┆ 257200     │
│ Albania ┆ 1987 ┆ female ┆ 35-54 years ┆ 6           ┆ 278800     │
│ Albania ┆ 1987 ┆ female ┆ 5-14 years  ┆ 0           ┆ 311000     │
│ Albania ┆ 1987 ┆ female ┆ 55-74 years ┆ 0           ┆ 144600     │
│ Albania ┆ 1987 ┆ female ┆ 75+ years   ┆ 1           ┆ 35600      │
└─────────┴──────┴────────┴─────────────┴─────────────┴────────────┘

Tutaj znów musimy zrobić krótką przerwę na uzupełnienie informacji technicznych. Poprzednio użyliśmy napisu `pl.read_csv(path_to_data)`, aby wywować funkcję `read_csv` z biblioteki `pl` (co jest naszym aliasem na `polars`). Teraz użwamy `df.drop_nulls()`, ale `df` nie jest tym razem żadną biblioteką! Jest tabelą typu `DataFrame`, co zatem może znaczyć ta kropka?

Na początek wysarczy wiedziec, że Python pozwala definiować funkcje powiązane z konkretnymi typami obieków, nazywane metodami. Metoda `drop_nulls` jest powiązana z obiektami `DataFrame` i zwraca obiekt `DataFrame` pozbawiony wszystkich wierszy w których występowały wartości `null`. Kropka między `df` a `drop_nulls` wskazuje z której tabeli powinny zostać usunięte wiersze.

Sprawdźmy jakie unikalne wartości kolumny `country` są dostępne w pliku.

In [8]:
unique_countries = df.select("country").unique()
unique_countries

shape: (141, 1)
┌──────────────────────────────┐
│ country                      │
│ ---                          │
│ str                          │
╞══════════════════════════════╡
│ Czech Republic               │
│ Turkmenistan                 │
│ Costa Rica                   │
│ United States of America     │
│ Saint Vincent and Grenadines │
│ …                            │
│ Armenia                      │
│ Barbados                     │
│ Virgin Islands (USA)         │
│ Syrian Arab Republic         │
│ Mayotte                      │
└──────────────────────────────┘

Najpierw wybraliśmy z tabeli tylko jedną kolumnę, a następnie pozwoliliśmy wyświetlać tylko unikalne wartości. Ale danych wciąż jest na tyle dużo, że `Polars` domyślnie pomija więcej wierszy. Możemy to obejść iterjąc po nich używając pętli `for`:

In [9]:
for country in unique_countries.rows():
    print(country)

('Czech Republic',)
('Turkmenistan',)
('Costa Rica',)
('United States of America',)
('Saint Vincent and Grenadines',)
('Rodrigues',)
('Italy',)
('Anguilla',)
('Turkey',)
('Ukraine',)
('Netherlands',)
('Tajikistan',)
('Fiji',)
('Monaco',)
('Bosnia and Herzegovina',)
('Cuba',)
('Zimbabwe',)
('Bahrain',)
('Reunion',)
('Ireland',)
('Belgium',)
('Finland',)
('Montenegro',)
('New Zealand',)
('Occupied Palestinian Territory',)
('Trinidad and Tobago',)
('Spain',)
('Maldives',)
('Mongolia',)
('Oman',)
('Thailand',)
('Latvia',)
('Georgia',)
('Iran (Islamic Rep of)',)
('Hungary',)
('Uzbekistan',)
('Austria',)
('Philippines',)
('Saint Lucia',)
('Israel',)
('Mauritius',)
('Estonia',)
('Luxembourg',)
('Haiti',)
('Guadeloupe',)
('Poland',)
('Falkland Islands (Malvinas)',)
('Belize',)
('France',)
('Peru',)
('Qatar',)
('TFYR Macedonia',)
('Paraguay',)
('Kiribati',)
('Honduras',)
('Aruba',)
('Egypt',)
('Portugal',)
('Dominican Republic',)
('Suriname',)
('Australia',)
('Venezuela (Bolivarian Republic of)',)
('Sweden',)
('Singapore',)
('Republic of Korea',)
('Malaysia',)
('Colombia',)
('Kyrgyzstan',)
('Belarus',)
('Serbia',)
('El Salvador',)
('Japan',)
('Bulgaria',)
('French Guiana',)
('San Marino',)
('Mexico',)
('United Arab Emirates',)
('Brazil',)
('Canada',)
('Guatemala',)
('Antigua and Barbuda',)
('Macau',)
('Chile',)
('Republic of Moldova',)
('Romania',)
('South Africa',)
('Puerto Rico',)
('Bolivia',)
('Sri Lanka',)
('Saudi Arabia',)
('Norway',)
('Morocco',)
('Guyana',)
('Tunisia',)
('Croatia',)
('Brunei Darussalam',)
('Ecuador',)
('Grenada',)
('Bahamas',)
('Denmark',)
('Kazakhstan',)
('Lithuania',)
('Sao Tome and Principe',)
('Panama',)
('Slovakia',)
('Hong Kong SAR',)
('Russian Federation',)
('Cyprus',)
('Albania',)
('Dominica',)
('Turks and Caicos Islands',)
('Martinique',)
('Jamaica',)
('Nicaragua',)
('Cabo Verde',)
('Azerbaijan',)
('Iraq',)
('Greece',)
('Saint Pierre and Miquelon',)
('Uruguay',)
('Netherlands Antilles',)
('United Kingdom',)
('Argentina',)
('Switzerland',)
('Slovenia',)
('British Virgin Islands',)
('Kuwait',)
('Iceland',)
('Jordan',)
('Saint Kitts and Nevis',)
('Cayman Islands',)
('Malta',)
('Germany',)
('Bermuda',)
('Seychelles',)
('Montserrat',)
('Armenia',)
('Barbados',)
('Virgin Islands (USA)',)
('Syrian Arab Republic',)
('Mayotte',)

Rozwiązanie to wciąż nie wygląda zbyt elegancko, ale nie będziemy się tym teraz przejmować. Był to przede wszystkim pretekst aby pokazać pętlę `for`. Pozwala ona iterować po wieloelementowych obiektach. Jednym z najczęściej spotykanych obiektów tego typu jest lista. Poniżej pokazujemy jak stworzyć bardzo prostą listę elementów i wypisać je używając pętli `for`. Najprostszym sposobem na stworzenie listy jest wypisanie jej elementów oddzielonych przecinkami w nawiasach kwadratowych.

In [10]:
nazwana_lista = ["siekiera", "motyka", "bimber", "szklanka"]
print("Lista potrzebnych przedmiotów:")
for przedmiot in nazwana_lista:
    print(przedmiot)
print("Wypisywanie listy zakończone")

Lista potrzebnych przedmiotów:
siekiera
motyka
bimber
szklanka
Wypisywanie listy zakończone

Przejdźmy przez każdą linijkę kodu powyżej:
1. Tworzymy listę i zapisujemy ją do zmiennej `nazwana_lista`
1. Wypisujemy `"Lista potrzebnych przedmiotów:"`
1. Inicjujemy pętlę, każdy element listy będzie po kolei przypisywany do zmiennej `przdmiot`.
1. Komendy wynokywane w czasie pętli oddzielone są tabulatorami
1. Po wykonaniu wszystkich przejść przez pętle wykonywany jest kod który znajduje się za nią – wypisanie `Wypisywanie listy zakończone`

Jak widać, kod wykonywany jest w kolejności. Zwróćmy również uwagę na fakt, że funkcja `print` nie wyświelka cudzysłowów w których zamknięte są stringi. Cudzysłowy te są bowiem częścią składni Pythona, a nie samego tekstu.

## Proste operacje na danych

Spróbujmy w końcu wyciągnąć coś użytecznego z danych, zacznijmy od wyfiltrowania wierszych dotyczących polski.

In [11]:
df_poland = df_clean.filter(pl.col("country") == "Poland")
df_poland.head(5)

shape: (5, 6)
┌─────────┬──────┬────────┬─────────────┬─────────────┬────────────┐
│ country ┆ year ┆ sex    ┆ age         ┆ suicides_no ┆ population │
│ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---         ┆ ---        │
│ str     ┆ i64  ┆ str    ┆ str         ┆ i64         ┆ i64        │
╞═════════╪══════╪════════╪═════════════╪═════════════╪════════════╡
│ Poland  ┆ 1983 ┆ female ┆ 15-24 years ┆ 120         ┆ 2695500    │
│ Poland  ┆ 1983 ┆ female ┆ 25-34 years ┆ 175         ┆ 3246500    │
│ Poland  ┆ 1983 ┆ female ┆ 35-54 years ┆ 246         ┆ 4280400    │
│ Poland  ┆ 1983 ┆ female ┆ 5-14 years  ┆ 8           ┆ 2821000    │
│ Poland  ┆ 1983 ┆ female ┆ 55-74 years ┆ 200         ┆ 3142500    │
└─────────┴──────┴────────┴─────────────┴─────────────┴────────────┘

A teraz wiersze dotyczące polskich kobiet.

In [12]:
df_f_poland = df_poland.filter(pl.col("sex") == "female")
df_f_poland

shape: (186, 6)
┌─────────┬──────┬────────┬─────────────┬─────────────┬────────────┐
│ country ┆ year ┆ sex    ┆ age         ┆ suicides_no ┆ population │
│ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---         ┆ ---        │
│ str     ┆ i64  ┆ str    ┆ str         ┆ i64         ┆ i64        │
╞═════════╪══════╪════════╪═════════════╪═════════════╪════════════╡
│ Poland  ┆ 1983 ┆ female ┆ 15-24 years ┆ 120         ┆ 2695500    │
│ Poland  ┆ 1983 ┆ female ┆ 25-34 years ┆ 175         ┆ 3246500    │
│ Poland  ┆ 1983 ┆ female ┆ 35-54 years ┆ 246         ┆ 4280400    │
│ Poland  ┆ 1983 ┆ female ┆ 5-14 years  ┆ 8           ┆ 2821000    │
│ Poland  ┆ 1983 ┆ female ┆ 55-74 years ┆ 200         ┆ 3142500    │
│ …       ┆ …    ┆ …      ┆ …           ┆ …           ┆ …          │
│ Poland  ┆ 2015 ┆ female ┆ 25-34 years ┆ 71          ┆ 2931931    │
│ Poland  ┆ 2015 ┆ female ┆ 35-54 years ┆ 256         ┆ 5143247    │
│ Poland  ┆ 2015 ┆ female ┆ 5-14 years  ┆ 7           ┆ 1855256    │
│ Poland  ┆ 2015 ┆ female ┆ 55-74 years ┆ 251         ┆ 4778252    │
│ Poland  ┆ 2015 ┆ female ┆ 75+ years   ┆ 77          ┆ 1790695    │
└─────────┴──────┴────────┴─────────────┴─────────────┴────────────┘

Możemy pogrupować dane według roku.

In [13]:
df_f_poland_grouped = df_f_poland.group_by("year").agg(pl.col("suicides_no").sum())
df_f_poland_grouped

shape: (31, 2)
┌──────┬─────────────┐
│ year ┆ suicides_no │
│ ---  ┆ ---         │
│ i64  ┆ i64         │
╞══════╪═════════════╡
│ 2007 ┆ 812         │
│ 1986 ┆ 849         │
│ 2002 ┆ 992         │
│ 2001 ┆ 850         │
│ 2010 ┆ 840         │
│ …    ┆ …           │
│ 2014 ┆ 811         │
│ 1994 ┆ 891         │
│ 1988 ┆ 841         │
│ 1996 ┆ 909         │
│ 1983 ┆ 805         │
└──────┴─────────────┘

Argumenty metody `agg` wskazują w jaki sposób mają być grupowane kolumny – w tym wypadku wartości `suicides_no` dla każdego roku są sumowane. 

Zobaczmy jak zmieniała się liczba samobójstw wśród kobiet w kolejnych latach. Będziemy potrzebować do tego biblioteki `plotly`.

In [15]:
import plotly.express as px

fig = px.line(df_f_poland_grouped, x="year", y="suicides_no")
fig.show()

Coś jest nie tak, dane rysowane są w kolejności wierszy, musimy je posortować.

In [17]:
df_f_poland_grouped = df_f_poland.group_by("year").agg(pl.col("suicides_no").sum()).sort("year")
df_f_poland_grouped.head(5)

shape: (5, 2)
┌──────┬─────────────┐
│ year ┆ suicides_no │
│ ---  ┆ ---         │
│ i64  ┆ i64         │
╞══════╪═════════════╡
│ 1983 ┆ 805         │
│ 1984 ┆ 925         │
│ 1985 ┆ 853         │
│ 1986 ┆ 849         │
│ 1987 ┆ 910         │
└──────┴─────────────┘

In [18]:
fig = px.line(df_f_poland_grouped, x="year", y="suicides_no")
fig.show()

Stwórzmy teraz jeden wykres, na którym będzie widać zarówno mężczyzn i kobiety. Jak widać, argumentem `group_by` może być lista

In [22]:
df_poland_grouped = df_poland.group_by(["year", "sex"]).agg(pl.col("suicides_no").sum()).sort("year")
df_poland_grouped.head(5)

shape: (5, 3)
┌──────┬────────┬─────────────┐
│ year ┆ sex    ┆ suicides_no │
│ ---  ┆ ---    ┆ ---         │
│ i64  ┆ str    ┆ i64         │
╞══════╪════════╪═════════════╡
│ 1983 ┆ male   ┆ 3730        │
│ 1983 ┆ female ┆ 805         │
│ 1984 ┆ female ┆ 925         │
│ 1984 ┆ male   ┆ 4242        │
│ 1985 ┆ male   ┆ 4092        │
└──────┴────────┴─────────────┘

In [30]:
fig = px.line(
    df_poland_grouped,
    x="year",
    y ="suicides_no",
    color="sex",
    title="Liczba samobójstw w Polsce w latach 1985-2016",
    labels={"year": "Rok", "suicides_no": "Liczba samobójstw", "sex": "Płeć"},
)
fig.show()

## Praca domowa

Pod adresem https://statystyka.policja.pl/download/20/270613/zamachysamobojczezakonczoneZGONEMmiejscapopelnienia2017-2025.xlsx znajdują się policyjne dane na temat samobójstw. Na ich podstawie przygtuj notatnik z wykresem przypominający powyższy – prezentujący liczbę samobójstw rok po roku z podziałem na mężczyzn i kobiety.

Wskazówki:
1. Plik na stronie policji jest dostępny w formacie xlsx; aby go otworzyć należy użyć metody `read_excel`.
1. Argumentem metody `read_excel` może być również link do pliku.